name = "ernisto/test"
version = "0.1.0-alpha.3"
description = "minimal test runner"
authors = ["ernisto <joaovitordesouza707@gmail.com>"]
license = "MIT"

workspace_members = ["lib", "cli/*"]
includes = [
    "pesde.toml",
    "README.md",
    "LICENSE",
]

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
environment = "lune"

[engines]
pesde = "^0.7.1"
