name = "ernisto/test"
version = "0.1.0-beta.5"
description = "minimal test runner"
authors = ["ernisto <joaovitordesouza707@gmail.com>"]
license = "MIT"
includes = [
    "pesde.toml",
    "LICENSE",
    ".luaurc",
    "**/*.luau",
]

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
environment = "lune"
lib = "lib.luau"
bin = "cli.luau"

[engines]
pesde = "^0.7.1"
lune = "^0.10.2"

[dependencies]
test = { name = "ernisto/testlib", version = "^0.1.0-beta.2", target = "luau" }
